org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.4
minecraft_version_range=[1.19.4,1.20)

forge_version=45.4.3
forge_version_range=[45,)
loader_version_range=[45,)

mapping_channel=official
mapping_version=1.19.4

mod_id=beetifulgarden
mod_name=Beetiful Garden
mod_license=LGPL v2.1
mod_version=1.19.4-1.1.0
mod_group_id=eu.wxrlds.beetifulgarden
mod_authors=Wxrlds
mod_description=Adds effect Beetroots
